### ISSUE TITLE
Bladder 1 issues

### ISSUE THREAD

**Issue by rchristie** [ABI-Software/scaffoldmaker#228]
Issues with bladder1 (with material coordinates) not addressed by PR #206 

- [x] Rat bladder is stretched in dorsal-ventral direction. Seems to be incorrect compared to bladder with urethra1.
- [x] Change all models to be approximately unit sized; make central path have centre of urethra junction at 0,0,0, with urethra pointing in -y.
- [x] Comment out flat coordinates as flat fitting is now effective. (Also isn’t a good representation for cat which is narrower nearer to urethra).
- [x] Add bladder1 tests. Currently only testing bladder with urethra.

**Comment by zekh167** [comment]
Hi Richard. 
Regarding the second comment, the central path for all species is already on x-y plane and the center of urethra junction placed at (0,0,0) with urethra pointing in almost -x. Why you prefer to have the urethra pointing to -y direction? What is the difference?

**Comment by zekh167** [comment]
The other point is that the bladder shape is almost the same in all species and the main difference is their dimensions. That is why I made the scaffolds in different sizes to better represent the difference between them. So, isn't it better to keep them in different sizes?
If you prefer to have them approximately in unite size, I can change the central path to make this, but then, all the scaffolds may look similar. Is it OK?

**Comment by zekh167** [comment]
I changed the last test_bladder file to only test the bladder. Then, created a new test file, named test_bladderurethra which testing bladder with urethra.

**Comment by zekh167** [comment]
I changed the central path for rat and human to make the shape better.

**Comment by zekh167** [comment]
I also commented out the flat coordinates as you suggested.
