### ISSUE TITLE
Add helper methods to scale scaffold

### ISSUE THREAD

**Issue by hsorby** [ABI-Software/scaffoldmaker#27]
It would be convenient to have some helper methods that can be used to scale the scaffold.

```
def scale_width(self, width):
    pass
def scale_height(self, width):
    pass
def scale_depth(self, width):
    pass
````

would be helpful.

**Comment by rchristie** [comment]
ScaffoldPackage now has the ability to scale, rotate and translate a scaffold. Resolved.
