### ISSUE TITLE
Edit 'data_coordinates' field for fiducial points

### ISSUE THREAD

**Issue by mahyar-osn** [ABI-Software/scaffoldmaker#53]
It would be very helpful to distinguish data points from segmented fiducial points by having a different field name from the current 'data_coordinates' to something else, for example 'fiducial_coordinates'.

**Comment by rchristie** [comment]
I'll change fields prefixed by 'data' to be prefixed by 'fiducial' e.g.:
fiducial_coordinates
fiducial_label
fiducial_element_xi

Note this change will require meshgeneratorstep to be updated.
